import React from "react";
import { Scale, X, AlertTriangle } from "lucide-react";

interface TermsOfUseModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const TermsOfUseModal: React.FC<TermsOfUseModalProps> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs">
      <div className="bg-white dark:bg-slate-900 rounded-3xl border border-slate-200 dark:border-slate-800 max-w-2xl w-full max-h-[85vh] flex flex-col shadow-2xl animate-in fade-in zoom-in-95 duration-200">
        
        {/* Modal Header */}
        <div className="flex items-center justify-between p-6 border-b border-slate-100 dark:border-slate-800">
          <div className="flex items-center space-x-3">
            <div className="p-2.5 rounded-xl bg-brand-50 dark:bg-brand-950 text-brand-600 dark:text-brand-400">
              <Scale className="w-6 h-6" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-slate-900 dark:text-white">Terms of Use & Disclaimer</h3>
              <p className="text-xs text-slate-500">Important legal terms regarding usage and limitation of liability</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-xl text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Scrollable Content Body */}
        <div className="p-6 overflow-y-auto space-y-4 text-xs text-slate-600 dark:text-slate-300 leading-relaxed">
          
          <div className="p-4 rounded-2xl bg-amber-50 dark:bg-amber-950/50 border border-amber-200 dark:border-amber-800 flex items-start space-x-3 text-amber-900 dark:text-amber-200">
            <AlertTriangle className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
            <div>
              <h4 className="font-semibold text-sm text-amber-900 dark:text-amber-100">
                Educational & Fun Demonstration Project Only
              </h4>
              <p className="mt-1 text-[11px] text-amber-800 dark:text-amber-300">
                This website and software are provided strictly as a fun, educational demonstration and research prototype. It is NOT an FDA-cleared medical device, does NOT provide medical advice, and MUST NOT be used to guide real patient clinical decisions.
              </p>
            </div>
          </div>

          <section className="space-y-1.5">
            <h4 className="font-bold text-slate-900 dark:text-white text-sm">1. No Accountability or Liability</h4>
            <p>
              The creators, authors, and contributors of AccuDose hold **zero accountability, liability, or responsibility** for any usage of this software, any decisions made based on its outputs, or any data inputted into the system. You agree that your use of this website is at your sole risk.
            </p>
          </section>

          <section className="space-y-1.5">
            <h4 className="font-bold text-slate-900 dark:text-white text-sm">2. Not Medical Advice or a Medical Device</h4>
            <p>
              All simulations, trajectories, drug concentrations, and confidence scores generated by this website are synthetic mathematical approximations. This platform does not diagnose, treat, cure, or prevent any disease, and cannot replace professional medical judgment from licensed physicians.
            </p>
          </section>

          <section className="space-y-1.5">
            <h4 className="font-bold text-slate-900 dark:text-white text-sm">3. Assumption of Risk & Indemnification</h4>
            <p>
              By accessing or using this website, you explicitly release the developers from any and all claims, demands, damages, liabilities, losses, or expenses (including legal fees) arising directly or indirectly from your interaction with the application.
            </p>
          </section>

          <section className="space-y-1.5">
            <h4 className="font-bold text-slate-900 dark:text-white text-sm">4. Modifications & Availability</h4>
            <p>
              We reserve the right to modify, suspend, or terminate access to this website at any time without notice. The software is provided "AS IS" and "AS AVAILABLE" without warranties of any kind.
            </p>
          </section>

        </div>

        {/* Modal Footer */}
        <div className="p-4 border-t border-slate-100 dark:border-slate-800 flex justify-end">
          <button
            type="button"
            onClick={onClose}
            className="py-2.5 px-6 rounded-xl bg-brand-600 hover:bg-brand-700 text-white font-semibold text-xs transition-all shadow-md shadow-brand-600/20"
          >
            I Understand & Agree
          </button>
        </div>

      </div>
    </div>
  );
};
